### ISSUE TITLE
다국어 지원, 디자인 수정 제안

### ISSUE THREAD

**Issue by KimEJ** [ubuntu-kr/blog#1]
- 외국어 포스트와 한국어 포스트가 따로 있으면 좋지 않을것 같습니다.
- 헤드라인 디자인이 가독성을 해칠것으로 우려됩니다. [이런 느낌으로](https://photos.app.goo.gl/CTsFuaSy8gg6THea8) 바꾸면 좋을것 같습니다

~~제가 고쳤으면 좋겠으나 하나도 모르는 관계로...~~

**Comment by sukso96100** [comment]
Hugo 기반으로 리뉴얼 하면서 대부분 반영되었습니다.
